[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem", "panic_immediate_abort"]

[build]
rustflags = ["-Cpanic=abort"]
# target = "aarch64-unknown-linux-none.json"
target = "x86_64-unknown-linux-none.json"
